name: dcli
version: 2.0.0-beta.17
homepage: https://dcli.onepub.dev
documentation: https://dcli.onepub.dev
description: Dart console SDK - write console (cli) apps/scripts using dart.
repository: https://github.com/onepub-dev/dcli
environment: 
  sdk: '>=2.18.0 <3.0.0'
dependencies: 
  _fe_analyzer_shared: ^27.0.0
  analyzer: ^3.3.0
  archive: ^3.2.2
  args: ^2.3.1
  async: ^2.8.2
  basic_utils: ^3.8.0
  boolean_selector: ^2.1.0
  charcode: ^1.3.1
  chunked_stream: ^1.4.1
  circular_buffer: ^0.11.0
  cli_util: ^0.3.5
  clock: ^1.1.1
  collection: ^1.16.0
  convert: ^3.0.1
  coverage: ^1.0.3
  crypto: ^3.0.1
  csv: ^5.0.1
  dart_console2: ^2.0.1
  dcli_core: ^2.0.0-beta.17
  equatable: ^2.0.3
  ffi: ^2.0.1
  file: ^6.1.2
  file_utils: ^1.0.1
  frontend_server_client: ^2.1.2
  functional_data: ^1.0.0
  glob: ^2.0.1
  globbing: ^1.0.0
  http: ^0.13.4
  http_multi_server: ^3.2.0
  http_parser: ^4.0.0
  ini: ^2.1.0
  intl: ^0.17.0
  io: ^1.0.3
  js: ^0.6.3
  json2yaml: ^3.0.0
  json_annotation: ^4.1.0
  logging: ^1.0.2
  matcher: ^0.12.11
  meta: ^1.7.0
  mime: ^1.0.1
  node_preamble: ^2.0.1
  package_config: ^2.0.2
  path: ^1.8.1
  pedantic: ^1.11.1
  pointycastle: ^3.5.2
  pool: ^1.5.0
  posix: ^4.1.0
  pub_semver: ^2.1.1
  pubspec2: ^2.4.1
  pubspec_lock: ^3.0.1
  quiver: ^3.0.1+1
  random_string: ^2.3.1
  scope: ^3.0.0
  settings_yaml: ^5.0.0-beta.2
  shelf: ^1.2.0
  shelf_packages_handler: ^3.0.0
  shelf_static: ^1.1.0
  shelf_web_socket: ^1.0.1
  source_map_stack_trace: ^2.1.0
  source_maps: ^0.10.10
  source_span: ^1.8.1
  stack_trace: ^1.10.0
  stream_channel: ^2.1.0
  string_scanner: ^1.1.0
  sum_types: ^0.3.2
  system_info2: ^2.0.3
  term_glyph: ^1.2.0
  test_api: ^0.4.9
  test_core: ^0.4.10
  typed_data: ^1.3.0
  uri: ^1.0.0
  uuid: ^3.0.6
  validators2: ^3.0.0
  vin_decoder: ^0.2.1-nullsafety
  vm_service: ^7.5.0
  watcher: ^1.0.0
  web_socket_channel: ^2.1.0
  webkit_inspection_protocol: ^1.0.0
  win32: ^3.1.1
  yaml: ^3.1.0
dev_dependencies: 
  hex: ^0.2.0
  lint_hard: ^2.1.1
  mocktail: ^0.3.0
  test: ^1.0.0
executables: 
  dcli: 
  dcli_complete: 
  dcli_install: 
platforms: 
  linux: 
  macos: 
  windows: 
